Window.SetBackgroundTopColor(0, 0, 0);
Window.SetBackgroundBottomColor(0, 0, 0);

image = Image("splash.png");
sw = Window.GetWidth();
sh = Window.GetHeight();
iw = image.GetWidth();
ih = image.GetHeight();

sx = sw / iw;
sy = sh / ih;
if (sy < sx) {
    scale = sy;
} else {
    scale = sx;
}

new_w = iw * scale;
new_h = ih * scale;

scaled = image.Scale(new_w, new_h);
sprite = Sprite(scaled);
sprite.SetX((sw - new_w) / 2);
sprite.SetY((sh - new_h) / 2);
sprite.SetZ(1);
